version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es
      - discovery.seed_hosts=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://es.tama.exa:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  django-app:
    build: news_gathering
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8003:8000"
    depends_on:
      - es
  celery:
    build: news_gathering
    command: celery -A news_gathering worker -l info
    depends_on:
      - redis
  celery-beat:
    build: news_gathering
    command: celery -A news_gathering beat -l info
    depends_on:
      - redis
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es
volumes:
  esdata:
#
#networks:
#  elastic:

